- members.html
- members_en.html
I've added a photo in members/photo and a description in html.
> add sakaue

- publication.html
- publication_en.html
- Fixed missing publication year
- added a new publications
> added and fixed publication

- src/app/research/page.mdx
Update, at least somewhat, the research description.
> Create a better research description

- src/app/members/members-data.ts
to Datatracker, blog and web page.
> Add a couple of links

- src/app/for-students/page.mdx
This needs a lot of work still...
> Very ragged cleanup of the "for students" page

- src/app/publications/international-conferences-with-proceedings.mdx
Update International Conferences with Proceedings: zigen's QuNet paper.
> int conferences with proceddings update

- src/app/publications/page.tsx
From #71, tried to fix spacing issue where the number of the list is clip on small device by add left padding to the list.
> Add left padding to the list

- src/app/publications/other-publications.mdx
> other publications update

- src/app/research/page.mdx
Some description of many of the things going on. Still just a start.
> Improve the research page

- src/app/publications/international-conferences-with-proceedings.mdx
Updated proceedings paper with OIST.
> International conferences update

- src/app/members/members-data.ts
Poramet san, Please update again!!!!
> Format Update again

- src/app/members/members-data.ts
Fixed the path to the profile picture
> Fixed the path to the profile picture

- src/app/members/members-data.ts
I'm the luckiest guy around, with health, family, and a great research group. I was very lucky to be encouraged to enter STEM, and lucky to find excellent mentors.
> Update my luck.

- src/app/members/page.tsx
Allows for scrolling on mobile devices
> Closes #135 responsive layout for mobile/wider screens. 

- src/app/publications/books.mdx
Updated Quantum Communications book with link to arXiv and abstract.
> michal book update

- src/app/useful-links/page.mdx
Rework Links page. Still needs work, but much better.
> Rework Links page.

- src/app/news.mdx
- src/app/publications/books.mdx
- src/app/publications/internet-drafts.mdx
- src/app/publications/page.tsx
- src/app/publications/rfcs.mdx
How we update and present news all needs to be rethought...
> Put our book in as top news item, add RFCs as pubs, fix minor Books bug.

- src/app/publications/page.tsx
- src/components/navigator.tsx
> Remove Google Scholar from pubs page

- src/app/publications/journal-papers.mdx
There may still be more, and drafts, etc. haven't been updated...
> Add three missing journal articles.

- src/app/publications/theses.mdx
> bob_upload

- src/app/members/members-data.ts
> voy add member

- src/app/members/members-data.ts
> Update bob profile

- src/app/members/members-data.ts
> Update junseo to B4

- src/app/members/members-data.ts
- src/app/publications/theses.mdx
update whit3z's profile card and upload thesis.
> update whit3z profile and add thesis
